### ISSUE TITLE
sorting each time you getAll

### ISSUE THREAD

**Issue by febael** [florya/notes-backend#1]
Why don't you keep Note s already sorted In-Memory? I suggest you use an In-memory relational DB.

**Comment by chrisport** [comment]
You are right, a TreeMap would be appropriate.
Yes, there will be in-memory db (h2 probably). I'm playing with Jooq currently to implement it. 
Please feel free to contribute.

**Comment by febael** [comment]
all right but I am an elite and costy developer. 
5€ /h
